### ISSUE TITLE
Error in Github Actions - CompileSwift normal arm64 (in target 'Charts' from project 'Charts')

### ISSUE THREAD

**Issue by yonchevgalin** [danielgindi/Charts#4953]
## What did you do?

I am using Charts in my app and I am trying to run a CI/CD pipeline in Github Actions. Charts is added to the project via SwiftPackageManager. 

Currently, the app builds and runs on my local machine, but when I am building in Github Actions, I am getting the following error:

`CompileSwift normal arm64 (in target 'Charts' from project 'Charts')`

Any idea how to fix this? The workflow files looks like this:

```
# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "features" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: xcodebuild clean build -workspace GSH.xcworkspace -scheme GSH CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
```

## Charts Environment

**Charts version/Branch/Commit Number: 4.0.2**
**Xcode version: 13.3**
**Swift version: 5.0**
**Platform(s) running Charts: iOS**
**macOS version running Xcode: macOS Monterey 12.6**
